version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: TestIt.sln
  verbosity: minimal
before_build:
    - cmd: dotnet restore TestIt.sln